apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-jenkins
spec:
  tls:
  - hosts:
    - 10.107.9.143
    secretName:
  rules:
  - host: 10.107.9.143
    http:
      paths:
      - path:
        backend:
          serviceName: jenkins-ci
          servicePort: 8080
